name = "capnp"
version = "0.1.1"
license = "MIT"
author = "Rohit Goswami"
maintainer = "rgoswami@ieee.org"
copyright = "Copyright 2026, Rohit Goswami"
description = "Native modern-Fortran implementation of Cap'n Proto serialization"

[build]
auto-executables = false
auto-tests = true
auto-examples = false

[library]
source-dir = "src"

[[executable]]
name = "capnpc-fortran"
source-dir = "app"
main = "main.f90"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

# Available to all fpm tests (not shipped as package dependency).
[dev-dependencies]
test-drive = { git = "https://github.com/fortran-lang/test-drive.git", tag = "v0.6.1" }
