!> Generated by capnpc-fortran from schema/rpc-twoparty.capnp. Do not edit.
module rpc_twoparty_capnp
   use capnp
   implicit none
   public

   integer, parameter :: SIDE_SERVER_E = 0
   integer, parameter :: SIDE_CLIENT_E = 1

   integer, parameter :: VAT_ID_DWORDS = 1
   integer, parameter :: VAT_ID_PWORDS = 0
   type :: vat_id_t
      type(capnp_ptr_t) :: p
   end type vat_id_t

   integer, parameter :: PROVISION_ID_DWORDS = 1
   integer, parameter :: PROVISION_ID_PWORDS = 0
   type :: provision_id_t
      type(capnp_ptr_t) :: p
   end type provision_id_t

   integer, parameter :: RECIPIENT_ID_DWORDS = 0
   integer, parameter :: RECIPIENT_ID_PWORDS = 0
   type :: recipient_id_t
      type(capnp_ptr_t) :: p
   end type recipient_id_t

   integer, parameter :: THIRD_PARTY_CAP_ID_DWORDS = 0
   integer, parameter :: THIRD_PARTY_CAP_ID_PWORDS = 0
   type :: third_party_cap_id_t
      type(capnp_ptr_t) :: p
   end type third_party_cap_id_t

   integer, parameter :: JOIN_KEY_PART_DWORDS = 1
   integer, parameter :: JOIN_KEY_PART_PWORDS = 0
   type :: join_key_part_t
      type(capnp_ptr_t) :: p
   end type join_key_part_t

   integer, parameter :: JOIN_RESULT_DWORDS = 1
   integer, parameter :: JOIN_RESULT_PWORDS = 1
   type :: join_result_t
      type(capnp_ptr_t) :: p
   end type join_result_t

contains

   function vat_id_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(vat_id_t) :: h
      h%p = capnp_new_struct(msg, VAT_ID_DWORDS, VAT_ID_PWORDS, err)
   end function vat_id_new

   function vat_id_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(vat_id_t) :: h
      h = vat_id_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function vat_id_new_root

   function vat_id_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(vat_id_t) :: h
      h%p = capnp_root(msg, err)
   end function vat_id_read_root

   function vat_id_side_get(h) result(v)
      type(vat_id_t), intent(in) :: h
      integer :: v
      v = int(capnp_get_u16(h%p, 0_int64))
   end function vat_id_side_get

   subroutine vat_id_side_set(h, v, err)
      type(vat_id_t), intent(in) :: h
      integer, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 0_int64, int(v, int32), err)
   end subroutine vat_id_side_set

   function provision_id_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(provision_id_t) :: h
      h%p = capnp_new_struct(msg, PROVISION_ID_DWORDS, PROVISION_ID_PWORDS, err)
   end function provision_id_new

   function provision_id_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(provision_id_t) :: h
      h = provision_id_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function provision_id_new_root

   function provision_id_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(provision_id_t) :: h
      h%p = capnp_root(msg, err)
   end function provision_id_read_root

   function provision_id_join_id_get(h) result(v)
      type(provision_id_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function provision_id_join_id_get

   subroutine provision_id_join_id_set(h, v, err)
      type(provision_id_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine provision_id_join_id_set

   function recipient_id_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(recipient_id_t) :: h
      h%p = capnp_new_struct(msg, RECIPIENT_ID_DWORDS, RECIPIENT_ID_PWORDS, err)
   end function recipient_id_new

   function recipient_id_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(recipient_id_t) :: h
      h = recipient_id_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function recipient_id_new_root

   function recipient_id_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(recipient_id_t) :: h
      h%p = capnp_root(msg, err)
   end function recipient_id_read_root

   function third_party_cap_id_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(third_party_cap_id_t) :: h
      h%p = capnp_new_struct(msg, THIRD_PARTY_CAP_ID_DWORDS, THIRD_PARTY_CAP_ID_PWORDS, err)
   end function third_party_cap_id_new

   function third_party_cap_id_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(third_party_cap_id_t) :: h
      h = third_party_cap_id_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function third_party_cap_id_new_root

   function third_party_cap_id_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(third_party_cap_id_t) :: h
      h%p = capnp_root(msg, err)
   end function third_party_cap_id_read_root

   function join_key_part_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(join_key_part_t) :: h
      h%p = capnp_new_struct(msg, JOIN_KEY_PART_DWORDS, JOIN_KEY_PART_PWORDS, err)
   end function join_key_part_new

   function join_key_part_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(join_key_part_t) :: h
      h = join_key_part_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function join_key_part_new_root

   function join_key_part_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(join_key_part_t) :: h
      h%p = capnp_root(msg, err)
   end function join_key_part_read_root

   function join_key_part_join_id_get(h) result(v)
      type(join_key_part_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function join_key_part_join_id_get

   subroutine join_key_part_join_id_set(h, v, err)
      type(join_key_part_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine join_key_part_join_id_set

   function join_key_part_part_count_get(h) result(v)
      type(join_key_part_t), intent(in) :: h
      integer(int32) :: v
      v = capnp_get_u16(h%p, 4_int64)
   end function join_key_part_part_count_get

   subroutine join_key_part_part_count_set(h, v, err)
      type(join_key_part_t), intent(in) :: h
      integer(int32), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 4_int64, v, err)
   end subroutine join_key_part_part_count_set

   function join_key_part_part_num_get(h) result(v)
      type(join_key_part_t), intent(in) :: h
      integer(int32) :: v
      v = capnp_get_u16(h%p, 6_int64)
   end function join_key_part_part_num_get

   subroutine join_key_part_part_num_set(h, v, err)
      type(join_key_part_t), intent(in) :: h
      integer(int32), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 6_int64, v, err)
   end subroutine join_key_part_part_num_set

   function join_result_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(join_result_t) :: h
      h%p = capnp_new_struct(msg, JOIN_RESULT_DWORDS, JOIN_RESULT_PWORDS, err)
   end function join_result_new

   function join_result_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(join_result_t) :: h
      h = join_result_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function join_result_new_root

   function join_result_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(join_result_t) :: h
      h%p = capnp_root(msg, err)
   end function join_result_read_root

   function join_result_join_id_get(h) result(v)
      type(join_result_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function join_result_join_id_get

   subroutine join_result_join_id_set(h, v, err)
      type(join_result_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine join_result_join_id_set

   function join_result_succeeded_get(h) result(v)
      type(join_result_t), intent(in) :: h
      logical :: v
      v = capnp_get_bool(h%p, 32_int64)
   end function join_result_succeeded_get

   subroutine join_result_succeeded_set(h, v, err)
      type(join_result_t), intent(in) :: h
      logical, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_bool(h%p, 32_int64, v, err)
   end subroutine join_result_succeeded_set

   function join_result_cap_get(h, err) result(q)
      type(join_result_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: q
      q = capnp_getp(h%p, 0, err)
   end function join_result_cap_get

   subroutine join_result_cap_set(h, q, err)
      type(join_result_t), intent(in) :: h
      type(capnp_ptr_t), intent(in) :: q
      integer, intent(out) :: err
      call capnp_setp(h%p, 0, q, err)
   end subroutine join_result_cap_set

end module rpc_twoparty_capnp
