!> Generated by capnpc-fortran from schema/rpc.capnp. Do not edit.
module rpc_capnp
   use capnp
   implicit none
   public

   integer, parameter :: MESSAGE_DWORDS = 1
   integer, parameter :: MESSAGE_PWORDS = 1
   type :: message_t
      type(capnp_ptr_t) :: p
   end type message_t
   integer, parameter :: MESSAGE_UNIMPLEMENTED_TAG = 0
   integer, parameter :: MESSAGE_ABORT_TAG = 1
   integer, parameter :: MESSAGE_CALL_TAG = 2
   integer, parameter :: MESSAGE_RETURN_TAG = 3
   integer, parameter :: MESSAGE_FINISH_TAG = 4
   integer, parameter :: MESSAGE_RESOLVE_TAG = 5
   integer, parameter :: MESSAGE_RELEASE_TAG = 6
   integer, parameter :: MESSAGE_OBSOLETE_SAVE_TAG = 7
   integer, parameter :: MESSAGE_BOOTSTRAP_TAG = 8
   integer, parameter :: MESSAGE_OBSOLETE_DELETE_TAG = 9
   integer, parameter :: MESSAGE_PROVIDE_TAG = 10
   integer, parameter :: MESSAGE_ACCEPT_TAG = 11
   integer, parameter :: MESSAGE_JOIN_TAG = 12
   integer, parameter :: MESSAGE_DISEMBARGO_TAG = 13

   integer, parameter :: EXCEPTION_DWORDS = 1
   integer, parameter :: EXCEPTION_PWORDS = 2
   type :: exception_t
      type(capnp_ptr_t) :: p
   end type exception_t

   integer, parameter :: CALL_DWORDS = 3
   integer, parameter :: CALL_PWORDS = 3
   type :: call_t
      type(capnp_ptr_t) :: p
   end type call_t
   integer, parameter :: CALL_SEND_RESULTS_TO_CALLER_TAG = 0
   integer, parameter :: CALL_SEND_RESULTS_TO_YOURSELF_TAG = 1
   integer, parameter :: CALL_SEND_RESULTS_TO_THIRD_PARTY_TAG = 2

   integer, parameter :: RETURN_DWORDS = 2
   integer, parameter :: RETURN_PWORDS = 1
   type :: return_t
      type(capnp_ptr_t) :: p
   end type return_t
   integer, parameter :: RETURN_RESULTS_TAG = 0
   integer, parameter :: RETURN_EXCEPTION_TAG = 1
   integer, parameter :: RETURN_CANCELED_TAG = 2
   integer, parameter :: RETURN_RESULTS_SENT_ELSEWHERE_TAG = 3
   integer, parameter :: RETURN_TAKE_FROM_OTHER_QUESTION_TAG = 4
   integer, parameter :: RETURN_ACCEPT_FROM_THIRD_PARTY_TAG = 5

   integer, parameter :: FINISH_DWORDS = 1
   integer, parameter :: FINISH_PWORDS = 0
   type :: finish_t
      type(capnp_ptr_t) :: p
   end type finish_t

   integer, parameter :: RESOLVE_DWORDS = 1
   integer, parameter :: RESOLVE_PWORDS = 1
   type :: resolve_t
      type(capnp_ptr_t) :: p
   end type resolve_t
   integer, parameter :: RESOLVE_CAP_TAG = 0
   integer, parameter :: RESOLVE_EXCEPTION_TAG = 1

   integer, parameter :: RELEASE_DWORDS = 1
   integer, parameter :: RELEASE_PWORDS = 0
   type :: release_t
      type(capnp_ptr_t) :: p
   end type release_t

   integer, parameter :: BOOTSTRAP_DWORDS = 1
   integer, parameter :: BOOTSTRAP_PWORDS = 1
   type :: bootstrap_t
      type(capnp_ptr_t) :: p
   end type bootstrap_t

   integer, parameter :: PROVIDE_DWORDS = 1
   integer, parameter :: PROVIDE_PWORDS = 2
   type :: provide_t
      type(capnp_ptr_t) :: p
   end type provide_t

   integer, parameter :: ACCEPT_DWORDS = 1
   integer, parameter :: ACCEPT_PWORDS = 1
   type :: accept_t
      type(capnp_ptr_t) :: p
   end type accept_t

   integer, parameter :: JOIN_DWORDS = 1
   integer, parameter :: JOIN_PWORDS = 2
   type :: join_t
      type(capnp_ptr_t) :: p
   end type join_t

   integer, parameter :: DISEMBARGO_DWORDS = 1
   integer, parameter :: DISEMBARGO_PWORDS = 1
   type :: disembargo_t
      type(capnp_ptr_t) :: p
   end type disembargo_t
   integer, parameter :: DISEMBARGO_CONTEXT_SENDER_LOOPBACK_TAG = 0
   integer, parameter :: DISEMBARGO_CONTEXT_RECEIVER_LOOPBACK_TAG = 1
   integer, parameter :: DISEMBARGO_CONTEXT_ACCEPT_TAG = 2
   integer, parameter :: DISEMBARGO_CONTEXT_PROVIDE_TAG = 3

   integer, parameter :: EXCEPTION_TYPE_FAILED_E = 0
   integer, parameter :: EXCEPTION_TYPE_OVERLOADED_E = 1
   integer, parameter :: EXCEPTION_TYPE_DISCONNECTED_E = 2
   integer, parameter :: EXCEPTION_TYPE_UNIMPLEMENTED_E = 3

   integer, parameter :: MESSAGE_TARGET_DWORDS = 1
   integer, parameter :: MESSAGE_TARGET_PWORDS = 1
   type :: message_target_t
      type(capnp_ptr_t) :: p
   end type message_target_t
   integer, parameter :: MESSAGE_TARGET_IMPORTED_CAP_TAG = 0
   integer, parameter :: MESSAGE_TARGET_PROMISED_ANSWER_TAG = 1

   integer, parameter :: PAYLOAD_DWORDS = 0
   integer, parameter :: PAYLOAD_PWORDS = 2
   type :: payload_t
      type(capnp_ptr_t) :: p
   end type payload_t

   integer, parameter :: PROMISED_ANSWER_DWORDS = 1
   integer, parameter :: PROMISED_ANSWER_PWORDS = 1
   type :: promised_answer_t
      type(capnp_ptr_t) :: p
   end type promised_answer_t

   integer, parameter :: PROMISED_ANSWER_OP_DWORDS = 1
   integer, parameter :: PROMISED_ANSWER_OP_PWORDS = 0
   type :: promised_answer_op_t
      type(capnp_ptr_t) :: p
   end type promised_answer_op_t
   integer, parameter :: PROMISED_ANSWER_OP_NOOP_TAG = 0
   integer, parameter :: PROMISED_ANSWER_OP_GET_POINTER_FIELD_TAG = 1

   integer, parameter :: CAP_DESCRIPTOR_DWORDS = 1
   integer, parameter :: CAP_DESCRIPTOR_PWORDS = 1
   type :: cap_descriptor_t
      type(capnp_ptr_t) :: p
   end type cap_descriptor_t
   integer, parameter :: CAP_DESCRIPTOR_NONE_TAG = 0
   integer, parameter :: CAP_DESCRIPTOR_SENDER_HOSTED_TAG = 1
   integer, parameter :: CAP_DESCRIPTOR_SENDER_PROMISE_TAG = 2
   integer, parameter :: CAP_DESCRIPTOR_RECEIVER_HOSTED_TAG = 3
   integer, parameter :: CAP_DESCRIPTOR_RECEIVER_ANSWER_TAG = 4
   integer, parameter :: CAP_DESCRIPTOR_THIRD_PARTY_HOSTED_TAG = 5

   integer, parameter :: THIRD_PARTY_CAP_DESCRIPTOR_DWORDS = 1
   integer, parameter :: THIRD_PARTY_CAP_DESCRIPTOR_PWORDS = 1
   type :: third_party_cap_descriptor_t
      type(capnp_ptr_t) :: p
   end type third_party_cap_descriptor_t

contains

   function message_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(message_t) :: h
      h%p = capnp_new_struct(msg, MESSAGE_DWORDS, MESSAGE_PWORDS, err)
   end function message_new

   function message_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(message_t) :: h
      h = message_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function message_new_root

   function message_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(message_t) :: h
      h%p = capnp_root(msg, err)
   end function message_read_root

   function message_which(h) result(tag)
      type(message_t), intent(in) :: h
      integer :: tag
      tag = int(capnp_get_u16(h%p, 0_int64))
   end function message_which

   function message_unimplemented_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(message_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_unimplemented_get

   function message_unimplemented_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(message_t) :: o
      call capnp_set_u16(h%p, 0_int64, 0_int32, err)
      o%p = capnp_new_struct(h%p%msg, MESSAGE_DWORDS, MESSAGE_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_unimplemented_init

   function message_abort_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(exception_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_abort_get

   function message_abort_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(exception_t) :: o
      call capnp_set_u16(h%p, 0_int64, 1_int32, err)
      o%p = capnp_new_struct(h%p%msg, EXCEPTION_DWORDS, EXCEPTION_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_abort_init

   function message_call_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(call_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_call_get

   function message_call_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(call_t) :: o
      call capnp_set_u16(h%p, 0_int64, 2_int32, err)
      o%p = capnp_new_struct(h%p%msg, CALL_DWORDS, CALL_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_call_init

   function message_return_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(return_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_return_get

   function message_return_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(return_t) :: o
      call capnp_set_u16(h%p, 0_int64, 3_int32, err)
      o%p = capnp_new_struct(h%p%msg, RETURN_DWORDS, RETURN_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_return_init

   function message_finish_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(finish_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_finish_get

   function message_finish_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(finish_t) :: o
      call capnp_set_u16(h%p, 0_int64, 4_int32, err)
      o%p = capnp_new_struct(h%p%msg, FINISH_DWORDS, FINISH_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_finish_init

   function message_resolve_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(resolve_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_resolve_get

   function message_resolve_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(resolve_t) :: o
      call capnp_set_u16(h%p, 0_int64, 5_int32, err)
      o%p = capnp_new_struct(h%p%msg, RESOLVE_DWORDS, RESOLVE_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_resolve_init

   function message_release_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(release_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_release_get

   function message_release_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(release_t) :: o
      call capnp_set_u16(h%p, 0_int64, 6_int32, err)
      o%p = capnp_new_struct(h%p%msg, RELEASE_DWORDS, RELEASE_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_release_init

   function message_obsolete_save_get(h, err) result(q)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: q
      q = capnp_getp(h%p, 0, err)
   end function message_obsolete_save_get

   subroutine message_obsolete_save_set(h, q, err)
      type(message_t), intent(in) :: h
      type(capnp_ptr_t), intent(in) :: q
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 0_int64, 7_int32, err)
      call capnp_setp(h%p, 0, q, err)
   end subroutine message_obsolete_save_set

   function message_bootstrap_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(bootstrap_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_bootstrap_get

   function message_bootstrap_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(bootstrap_t) :: o
      call capnp_set_u16(h%p, 0_int64, 8_int32, err)
      o%p = capnp_new_struct(h%p%msg, BOOTSTRAP_DWORDS, BOOTSTRAP_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_bootstrap_init

   function message_obsolete_delete_get(h, err) result(q)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: q
      q = capnp_getp(h%p, 0, err)
   end function message_obsolete_delete_get

   subroutine message_obsolete_delete_set(h, q, err)
      type(message_t), intent(in) :: h
      type(capnp_ptr_t), intent(in) :: q
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 0_int64, 9_int32, err)
      call capnp_setp(h%p, 0, q, err)
   end subroutine message_obsolete_delete_set

   function message_provide_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(provide_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_provide_get

   function message_provide_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(provide_t) :: o
      call capnp_set_u16(h%p, 0_int64, 10_int32, err)
      o%p = capnp_new_struct(h%p%msg, PROVIDE_DWORDS, PROVIDE_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_provide_init

   function message_accept_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(accept_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_accept_get

   function message_accept_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(accept_t) :: o
      call capnp_set_u16(h%p, 0_int64, 11_int32, err)
      o%p = capnp_new_struct(h%p%msg, ACCEPT_DWORDS, ACCEPT_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_accept_init

   function message_join_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(join_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_join_get

   function message_join_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(join_t) :: o
      call capnp_set_u16(h%p, 0_int64, 12_int32, err)
      o%p = capnp_new_struct(h%p%msg, JOIN_DWORDS, JOIN_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_join_init

   function message_disembargo_get(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(disembargo_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_disembargo_get

   function message_disembargo_init(h, err) result(o)
      type(message_t), intent(in) :: h
      integer, intent(out) :: err
      type(disembargo_t) :: o
      call capnp_set_u16(h%p, 0_int64, 13_int32, err)
      o%p = capnp_new_struct(h%p%msg, DISEMBARGO_DWORDS, DISEMBARGO_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_disembargo_init

   function exception_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(exception_t) :: h
      h%p = capnp_new_struct(msg, EXCEPTION_DWORDS, EXCEPTION_PWORDS, err)
   end function exception_new

   function exception_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(exception_t) :: h
      h = exception_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function exception_new_root

   function exception_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(exception_t) :: h
      h%p = capnp_root(msg, err)
   end function exception_read_root

   subroutine exception_reason_get(h, s, err)
      type(exception_t), intent(in) :: h
      character(len=:), allocatable, intent(out) :: s
      integer, intent(out) :: err
      call capnp_get_text(h%p, 0, s, err)
   end subroutine exception_reason_get

   subroutine exception_reason_set(h, s, err)
      type(exception_t), intent(in) :: h
      character(len=*), intent(in) :: s
      integer, intent(out) :: err
      call capnp_set_text(h%p, 0, s, err)
   end subroutine exception_reason_set

   function exception_obsolete_is_callers_fault_get(h) result(v)
      type(exception_t), intent(in) :: h
      logical :: v
      v = capnp_get_bool(h%p, 0_int64)
   end function exception_obsolete_is_callers_fault_get

   subroutine exception_obsolete_is_callers_fault_set(h, v, err)
      type(exception_t), intent(in) :: h
      logical, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_bool(h%p, 0_int64, v, err)
   end subroutine exception_obsolete_is_callers_fault_set

   function exception_obsolete_durability_get(h) result(v)
      type(exception_t), intent(in) :: h
      integer(int32) :: v
      v = capnp_get_u16(h%p, 2_int64)
   end function exception_obsolete_durability_get

   subroutine exception_obsolete_durability_set(h, v, err)
      type(exception_t), intent(in) :: h
      integer(int32), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 2_int64, v, err)
   end subroutine exception_obsolete_durability_set

   function exception_type_get(h) result(v)
      type(exception_t), intent(in) :: h
      integer :: v
      v = int(capnp_get_u16(h%p, 4_int64))
   end function exception_type_get

   subroutine exception_type_set(h, v, err)
      type(exception_t), intent(in) :: h
      integer, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 4_int64, int(v, int32), err)
   end subroutine exception_type_set

   subroutine exception_trace_get(h, s, err)
      type(exception_t), intent(in) :: h
      character(len=:), allocatable, intent(out) :: s
      integer, intent(out) :: err
      call capnp_get_text(h%p, 1, s, err)
   end subroutine exception_trace_get

   subroutine exception_trace_set(h, s, err)
      type(exception_t), intent(in) :: h
      character(len=*), intent(in) :: s
      integer, intent(out) :: err
      call capnp_set_text(h%p, 1, s, err)
   end subroutine exception_trace_set

   function call_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(call_t) :: h
      h%p = capnp_new_struct(msg, CALL_DWORDS, CALL_PWORDS, err)
   end function call_new

   function call_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(call_t) :: h
      h = call_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function call_new_root

   function call_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(call_t) :: h
      h%p = capnp_root(msg, err)
   end function call_read_root

   function call_question_id_get(h) result(v)
      type(call_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function call_question_id_get

   subroutine call_question_id_set(h, v, err)
      type(call_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine call_question_id_set

   function call_target_get(h, err) result(o)
      type(call_t), intent(in) :: h
      integer, intent(out) :: err
      type(message_target_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function call_target_get

   function call_target_init(h, err) result(o)
      type(call_t), intent(in) :: h
      integer, intent(out) :: err
      type(message_target_t) :: o
      o%p = capnp_new_struct(h%p%msg, MESSAGE_TARGET_DWORDS, MESSAGE_TARGET_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function call_target_init

   function call_interface_id_get(h) result(v)
      type(call_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_i64(h%p, 8_int64)
   end function call_interface_id_get

   subroutine call_interface_id_set(h, v, err)
      type(call_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_i64(h%p, 8_int64, v, err)
   end subroutine call_interface_id_set

   function call_method_id_get(h) result(v)
      type(call_t), intent(in) :: h
      integer(int32) :: v
      v = capnp_get_u16(h%p, 4_int64)
   end function call_method_id_get

   subroutine call_method_id_set(h, v, err)
      type(call_t), intent(in) :: h
      integer(int32), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 4_int64, v, err)
   end subroutine call_method_id_set

   function call_params_get(h, err) result(o)
      type(call_t), intent(in) :: h
      integer, intent(out) :: err
      type(payload_t) :: o
      o%p = capnp_getp(h%p, 1, err)
   end function call_params_get

   function call_params_init(h, err) result(o)
      type(call_t), intent(in) :: h
      integer, intent(out) :: err
      type(payload_t) :: o
      o%p = capnp_new_struct(h%p%msg, PAYLOAD_DWORDS, PAYLOAD_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 1, o%p, err)
   end function call_params_init

   function call_send_results_to_which(h) result(tag)
      type(call_t), intent(in) :: h
      integer :: tag
      tag = int(capnp_get_u16(h%p, 6_int64))
   end function call_send_results_to_which

   subroutine call_send_results_to_caller_set(h, err)
      type(call_t), intent(in) :: h
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 6_int64, 0_int32, err)
   end subroutine call_send_results_to_caller_set

   subroutine call_send_results_to_yourself_set(h, err)
      type(call_t), intent(in) :: h
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 6_int64, 1_int32, err)
   end subroutine call_send_results_to_yourself_set

   function call_send_results_to_third_party_get(h, err) result(q)
      type(call_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: q
      q = capnp_getp(h%p, 2, err)
   end function call_send_results_to_third_party_get

   subroutine call_send_results_to_third_party_set(h, q, err)
      type(call_t), intent(in) :: h
      type(capnp_ptr_t), intent(in) :: q
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 6_int64, 2_int32, err)
      call capnp_setp(h%p, 2, q, err)
   end subroutine call_send_results_to_third_party_set

   function call_allow_third_party_tail_call_get(h) result(v)
      type(call_t), intent(in) :: h
      logical :: v
      v = capnp_get_bool(h%p, 128_int64)
   end function call_allow_third_party_tail_call_get

   subroutine call_allow_third_party_tail_call_set(h, v, err)
      type(call_t), intent(in) :: h
      logical, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_bool(h%p, 128_int64, v, err)
   end subroutine call_allow_third_party_tail_call_set

   function call_no_promise_pipelining_get(h) result(v)
      type(call_t), intent(in) :: h
      logical :: v
      v = capnp_get_bool(h%p, 129_int64)
   end function call_no_promise_pipelining_get

   subroutine call_no_promise_pipelining_set(h, v, err)
      type(call_t), intent(in) :: h
      logical, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_bool(h%p, 129_int64, v, err)
   end subroutine call_no_promise_pipelining_set

   function call_only_promise_pipeline_get(h) result(v)
      type(call_t), intent(in) :: h
      logical :: v
      v = capnp_get_bool(h%p, 130_int64)
   end function call_only_promise_pipeline_get

   subroutine call_only_promise_pipeline_set(h, v, err)
      type(call_t), intent(in) :: h
      logical, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_bool(h%p, 130_int64, v, err)
   end subroutine call_only_promise_pipeline_set

   function return_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(return_t) :: h
      h%p = capnp_new_struct(msg, RETURN_DWORDS, RETURN_PWORDS, err)
   end function return_new

   function return_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(return_t) :: h
      h = return_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function return_new_root

   function return_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(return_t) :: h
      h%p = capnp_root(msg, err)
   end function return_read_root

   function return_which(h) result(tag)
      type(return_t), intent(in) :: h
      integer :: tag
      tag = int(capnp_get_u16(h%p, 6_int64))
   end function return_which

   function return_answer_id_get(h) result(v)
      type(return_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function return_answer_id_get

   subroutine return_answer_id_set(h, v, err)
      type(return_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine return_answer_id_set

   function return_release_param_caps_get(h) result(v)
      type(return_t), intent(in) :: h
      logical :: v
      v = capnp_get_bool(h%p, 32_int64, default=.true.)
   end function return_release_param_caps_get

   subroutine return_release_param_caps_set(h, v, err)
      type(return_t), intent(in) :: h
      logical, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_bool(h%p, 32_int64, v, err, default=.true.)
   end subroutine return_release_param_caps_set

   function return_results_get(h, err) result(o)
      type(return_t), intent(in) :: h
      integer, intent(out) :: err
      type(payload_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function return_results_get

   function return_results_init(h, err) result(o)
      type(return_t), intent(in) :: h
      integer, intent(out) :: err
      type(payload_t) :: o
      call capnp_set_u16(h%p, 6_int64, 0_int32, err)
      o%p = capnp_new_struct(h%p%msg, PAYLOAD_DWORDS, PAYLOAD_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function return_results_init

   function return_exception_get(h, err) result(o)
      type(return_t), intent(in) :: h
      integer, intent(out) :: err
      type(exception_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function return_exception_get

   function return_exception_init(h, err) result(o)
      type(return_t), intent(in) :: h
      integer, intent(out) :: err
      type(exception_t) :: o
      call capnp_set_u16(h%p, 6_int64, 1_int32, err)
      o%p = capnp_new_struct(h%p%msg, EXCEPTION_DWORDS, EXCEPTION_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function return_exception_init

   subroutine return_canceled_set(h, err)
      type(return_t), intent(in) :: h
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 6_int64, 2_int32, err)
   end subroutine return_canceled_set

   subroutine return_results_sent_elsewhere_set(h, err)
      type(return_t), intent(in) :: h
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 6_int64, 3_int32, err)
   end subroutine return_results_sent_elsewhere_set

   function return_take_from_other_question_get(h) result(v)
      type(return_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 8_int64)
   end function return_take_from_other_question_get

   subroutine return_take_from_other_question_set(h, v, err)
      type(return_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 6_int64, 4_int32, err)
      call capnp_set_u32(h%p, 8_int64, v, err)
   end subroutine return_take_from_other_question_set

   function return_accept_from_third_party_get(h, err) result(q)
      type(return_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: q
      q = capnp_getp(h%p, 0, err)
   end function return_accept_from_third_party_get

   subroutine return_accept_from_third_party_set(h, q, err)
      type(return_t), intent(in) :: h
      type(capnp_ptr_t), intent(in) :: q
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 6_int64, 5_int32, err)
      call capnp_setp(h%p, 0, q, err)
   end subroutine return_accept_from_third_party_set

   function return_no_finish_needed_get(h) result(v)
      type(return_t), intent(in) :: h
      logical :: v
      v = capnp_get_bool(h%p, 33_int64)
   end function return_no_finish_needed_get

   subroutine return_no_finish_needed_set(h, v, err)
      type(return_t), intent(in) :: h
      logical, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_bool(h%p, 33_int64, v, err)
   end subroutine return_no_finish_needed_set

   function finish_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(finish_t) :: h
      h%p = capnp_new_struct(msg, FINISH_DWORDS, FINISH_PWORDS, err)
   end function finish_new

   function finish_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(finish_t) :: h
      h = finish_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function finish_new_root

   function finish_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(finish_t) :: h
      h%p = capnp_root(msg, err)
   end function finish_read_root

   function finish_question_id_get(h) result(v)
      type(finish_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function finish_question_id_get

   subroutine finish_question_id_set(h, v, err)
      type(finish_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine finish_question_id_set

   function finish_release_result_caps_get(h) result(v)
      type(finish_t), intent(in) :: h
      logical :: v
      v = capnp_get_bool(h%p, 32_int64, default=.true.)
   end function finish_release_result_caps_get

   subroutine finish_release_result_caps_set(h, v, err)
      type(finish_t), intent(in) :: h
      logical, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_bool(h%p, 32_int64, v, err, default=.true.)
   end subroutine finish_release_result_caps_set

   function finish_require_early_cancellation_workaround_get(h) result(v)
      type(finish_t), intent(in) :: h
      logical :: v
      v = capnp_get_bool(h%p, 33_int64, default=.true.)
   end function finish_require_early_cancellation_workaround_get

   subroutine finish_require_early_cancellation_workaround_set(h, v, err)
      type(finish_t), intent(in) :: h
      logical, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_bool(h%p, 33_int64, v, err, default=.true.)
   end subroutine finish_require_early_cancellation_workaround_set

   function resolve_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(resolve_t) :: h
      h%p = capnp_new_struct(msg, RESOLVE_DWORDS, RESOLVE_PWORDS, err)
   end function resolve_new

   function resolve_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(resolve_t) :: h
      h = resolve_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function resolve_new_root

   function resolve_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(resolve_t) :: h
      h%p = capnp_root(msg, err)
   end function resolve_read_root

   function resolve_which(h) result(tag)
      type(resolve_t), intent(in) :: h
      integer :: tag
      tag = int(capnp_get_u16(h%p, 4_int64))
   end function resolve_which

   function resolve_promise_id_get(h) result(v)
      type(resolve_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function resolve_promise_id_get

   subroutine resolve_promise_id_set(h, v, err)
      type(resolve_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine resolve_promise_id_set

   function resolve_cap_get(h, err) result(o)
      type(resolve_t), intent(in) :: h
      integer, intent(out) :: err
      type(cap_descriptor_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function resolve_cap_get

   function resolve_cap_init(h, err) result(o)
      type(resolve_t), intent(in) :: h
      integer, intent(out) :: err
      type(cap_descriptor_t) :: o
      call capnp_set_u16(h%p, 4_int64, 0_int32, err)
      o%p = capnp_new_struct(h%p%msg, CAP_DESCRIPTOR_DWORDS, CAP_DESCRIPTOR_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function resolve_cap_init

   function resolve_exception_get(h, err) result(o)
      type(resolve_t), intent(in) :: h
      integer, intent(out) :: err
      type(exception_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function resolve_exception_get

   function resolve_exception_init(h, err) result(o)
      type(resolve_t), intent(in) :: h
      integer, intent(out) :: err
      type(exception_t) :: o
      call capnp_set_u16(h%p, 4_int64, 1_int32, err)
      o%p = capnp_new_struct(h%p%msg, EXCEPTION_DWORDS, EXCEPTION_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function resolve_exception_init

   function release_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(release_t) :: h
      h%p = capnp_new_struct(msg, RELEASE_DWORDS, RELEASE_PWORDS, err)
   end function release_new

   function release_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(release_t) :: h
      h = release_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function release_new_root

   function release_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(release_t) :: h
      h%p = capnp_root(msg, err)
   end function release_read_root

   function release_id_get(h) result(v)
      type(release_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function release_id_get

   subroutine release_id_set(h, v, err)
      type(release_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine release_id_set

   function release_reference_count_get(h) result(v)
      type(release_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 4_int64)
   end function release_reference_count_get

   subroutine release_reference_count_set(h, v, err)
      type(release_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 4_int64, v, err)
   end subroutine release_reference_count_set

   function bootstrap_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(bootstrap_t) :: h
      h%p = capnp_new_struct(msg, BOOTSTRAP_DWORDS, BOOTSTRAP_PWORDS, err)
   end function bootstrap_new

   function bootstrap_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(bootstrap_t) :: h
      h = bootstrap_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function bootstrap_new_root

   function bootstrap_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(bootstrap_t) :: h
      h%p = capnp_root(msg, err)
   end function bootstrap_read_root

   function bootstrap_question_id_get(h) result(v)
      type(bootstrap_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function bootstrap_question_id_get

   subroutine bootstrap_question_id_set(h, v, err)
      type(bootstrap_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine bootstrap_question_id_set

   function bootstrap_deprecated_object_id_get(h, err) result(q)
      type(bootstrap_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: q
      q = capnp_getp(h%p, 0, err)
   end function bootstrap_deprecated_object_id_get

   subroutine bootstrap_deprecated_object_id_set(h, q, err)
      type(bootstrap_t), intent(in) :: h
      type(capnp_ptr_t), intent(in) :: q
      integer, intent(out) :: err
      call capnp_setp(h%p, 0, q, err)
   end subroutine bootstrap_deprecated_object_id_set

   function provide_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(provide_t) :: h
      h%p = capnp_new_struct(msg, PROVIDE_DWORDS, PROVIDE_PWORDS, err)
   end function provide_new

   function provide_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(provide_t) :: h
      h = provide_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function provide_new_root

   function provide_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(provide_t) :: h
      h%p = capnp_root(msg, err)
   end function provide_read_root

   function provide_question_id_get(h) result(v)
      type(provide_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function provide_question_id_get

   subroutine provide_question_id_set(h, v, err)
      type(provide_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine provide_question_id_set

   function provide_target_get(h, err) result(o)
      type(provide_t), intent(in) :: h
      integer, intent(out) :: err
      type(message_target_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function provide_target_get

   function provide_target_init(h, err) result(o)
      type(provide_t), intent(in) :: h
      integer, intent(out) :: err
      type(message_target_t) :: o
      o%p = capnp_new_struct(h%p%msg, MESSAGE_TARGET_DWORDS, MESSAGE_TARGET_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function provide_target_init

   function provide_recipient_get(h, err) result(q)
      type(provide_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: q
      q = capnp_getp(h%p, 1, err)
   end function provide_recipient_get

   subroutine provide_recipient_set(h, q, err)
      type(provide_t), intent(in) :: h
      type(capnp_ptr_t), intent(in) :: q
      integer, intent(out) :: err
      call capnp_setp(h%p, 1, q, err)
   end subroutine provide_recipient_set

   function accept_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(accept_t) :: h
      h%p = capnp_new_struct(msg, ACCEPT_DWORDS, ACCEPT_PWORDS, err)
   end function accept_new

   function accept_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(accept_t) :: h
      h = accept_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function accept_new_root

   function accept_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(accept_t) :: h
      h%p = capnp_root(msg, err)
   end function accept_read_root

   function accept_question_id_get(h) result(v)
      type(accept_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function accept_question_id_get

   subroutine accept_question_id_set(h, v, err)
      type(accept_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine accept_question_id_set

   function accept_provision_get(h, err) result(q)
      type(accept_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: q
      q = capnp_getp(h%p, 0, err)
   end function accept_provision_get

   subroutine accept_provision_set(h, q, err)
      type(accept_t), intent(in) :: h
      type(capnp_ptr_t), intent(in) :: q
      integer, intent(out) :: err
      call capnp_setp(h%p, 0, q, err)
   end subroutine accept_provision_set

   function accept_embargo_get(h) result(v)
      type(accept_t), intent(in) :: h
      logical :: v
      v = capnp_get_bool(h%p, 32_int64)
   end function accept_embargo_get

   subroutine accept_embargo_set(h, v, err)
      type(accept_t), intent(in) :: h
      logical, intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_bool(h%p, 32_int64, v, err)
   end subroutine accept_embargo_set

   function join_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(join_t) :: h
      h%p = capnp_new_struct(msg, JOIN_DWORDS, JOIN_PWORDS, err)
   end function join_new

   function join_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(join_t) :: h
      h = join_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function join_new_root

   function join_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(join_t) :: h
      h%p = capnp_root(msg, err)
   end function join_read_root

   function join_question_id_get(h) result(v)
      type(join_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function join_question_id_get

   subroutine join_question_id_set(h, v, err)
      type(join_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine join_question_id_set

   function join_target_get(h, err) result(o)
      type(join_t), intent(in) :: h
      integer, intent(out) :: err
      type(message_target_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function join_target_get

   function join_target_init(h, err) result(o)
      type(join_t), intent(in) :: h
      integer, intent(out) :: err
      type(message_target_t) :: o
      o%p = capnp_new_struct(h%p%msg, MESSAGE_TARGET_DWORDS, MESSAGE_TARGET_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function join_target_init

   function join_key_part_get(h, err) result(q)
      type(join_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: q
      q = capnp_getp(h%p, 1, err)
   end function join_key_part_get

   subroutine join_key_part_set(h, q, err)
      type(join_t), intent(in) :: h
      type(capnp_ptr_t), intent(in) :: q
      integer, intent(out) :: err
      call capnp_setp(h%p, 1, q, err)
   end subroutine join_key_part_set

   function disembargo_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(disembargo_t) :: h
      h%p = capnp_new_struct(msg, DISEMBARGO_DWORDS, DISEMBARGO_PWORDS, err)
   end function disembargo_new

   function disembargo_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(disembargo_t) :: h
      h = disembargo_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function disembargo_new_root

   function disembargo_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(disembargo_t) :: h
      h%p = capnp_root(msg, err)
   end function disembargo_read_root

   function disembargo_target_get(h, err) result(o)
      type(disembargo_t), intent(in) :: h
      integer, intent(out) :: err
      type(message_target_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function disembargo_target_get

   function disembargo_target_init(h, err) result(o)
      type(disembargo_t), intent(in) :: h
      integer, intent(out) :: err
      type(message_target_t) :: o
      o%p = capnp_new_struct(h%p%msg, MESSAGE_TARGET_DWORDS, MESSAGE_TARGET_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function disembargo_target_init

   function disembargo_context_which(h) result(tag)
      type(disembargo_t), intent(in) :: h
      integer :: tag
      tag = int(capnp_get_u16(h%p, 4_int64))
   end function disembargo_context_which

   function disembargo_context_sender_loopback_get(h) result(v)
      type(disembargo_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function disembargo_context_sender_loopback_get

   subroutine disembargo_context_sender_loopback_set(h, v, err)
      type(disembargo_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 4_int64, 0_int32, err)
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine disembargo_context_sender_loopback_set

   function disembargo_context_receiver_loopback_get(h) result(v)
      type(disembargo_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function disembargo_context_receiver_loopback_get

   subroutine disembargo_context_receiver_loopback_set(h, v, err)
      type(disembargo_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 4_int64, 1_int32, err)
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine disembargo_context_receiver_loopback_set

   subroutine disembargo_context_accept_set(h, err)
      type(disembargo_t), intent(in) :: h
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 4_int64, 2_int32, err)
   end subroutine disembargo_context_accept_set

   function disembargo_context_provide_get(h) result(v)
      type(disembargo_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function disembargo_context_provide_get

   subroutine disembargo_context_provide_set(h, v, err)
      type(disembargo_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 4_int64, 3_int32, err)
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine disembargo_context_provide_set

   function message_target_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(message_target_t) :: h
      h%p = capnp_new_struct(msg, MESSAGE_TARGET_DWORDS, MESSAGE_TARGET_PWORDS, err)
   end function message_target_new

   function message_target_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(message_target_t) :: h
      h = message_target_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function message_target_new_root

   function message_target_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(message_target_t) :: h
      h%p = capnp_root(msg, err)
   end function message_target_read_root

   function message_target_which(h) result(tag)
      type(message_target_t), intent(in) :: h
      integer :: tag
      tag = int(capnp_get_u16(h%p, 4_int64))
   end function message_target_which

   function message_target_imported_cap_get(h) result(v)
      type(message_target_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function message_target_imported_cap_get

   subroutine message_target_imported_cap_set(h, v, err)
      type(message_target_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 4_int64, 0_int32, err)
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine message_target_imported_cap_set

   function message_target_promised_answer_get(h, err) result(o)
      type(message_target_t), intent(in) :: h
      integer, intent(out) :: err
      type(promised_answer_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function message_target_promised_answer_get

   function message_target_promised_answer_init(h, err) result(o)
      type(message_target_t), intent(in) :: h
      integer, intent(out) :: err
      type(promised_answer_t) :: o
      call capnp_set_u16(h%p, 4_int64, 1_int32, err)
      o%p = capnp_new_struct(h%p%msg, PROMISED_ANSWER_DWORDS, PROMISED_ANSWER_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function message_target_promised_answer_init

   function payload_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(payload_t) :: h
      h%p = capnp_new_struct(msg, PAYLOAD_DWORDS, PAYLOAD_PWORDS, err)
   end function payload_new

   function payload_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(payload_t) :: h
      h = payload_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function payload_new_root

   function payload_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(payload_t) :: h
      h%p = capnp_root(msg, err)
   end function payload_read_root

   function payload_content_get(h, err) result(q)
      type(payload_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: q
      q = capnp_getp(h%p, 0, err)
   end function payload_content_get

   subroutine payload_content_set(h, q, err)
      type(payload_t), intent(in) :: h
      type(capnp_ptr_t), intent(in) :: q
      integer, intent(out) :: err
      call capnp_setp(h%p, 0, q, err)
   end subroutine payload_content_set

   function payload_cap_table_get(h, err) result(l)
      type(payload_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: l
      l = capnp_getp(h%p, 1, err)
   end function payload_cap_table_get

   function payload_cap_table_get_elem(h, i, err) result(o)
      type(payload_t), intent(in) :: h
      integer, intent(in) :: i
      integer, intent(out) :: err
      type(cap_descriptor_t) :: o
      type(capnp_ptr_t) :: l
      l = capnp_getp(h%p, 1, err)
      if (err == CAPNP_OK) o%p = capnp_list_get_struct(l, i, err)
   end function payload_cap_table_get_elem

   function payload_cap_table_init(h, n, err) result(l)
      type(payload_t), intent(in) :: h
      integer(int64), intent(in) :: n
      integer, intent(out) :: err
      type(capnp_ptr_t) :: l
      l = capnp_new_composite_list(h%p%msg, n, CAP_DESCRIPTOR_DWORDS, CAP_DESCRIPTOR_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 1, l, err)
   end function payload_cap_table_init

   function promised_answer_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(promised_answer_t) :: h
      h%p = capnp_new_struct(msg, PROMISED_ANSWER_DWORDS, PROMISED_ANSWER_PWORDS, err)
   end function promised_answer_new

   function promised_answer_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(promised_answer_t) :: h
      h = promised_answer_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function promised_answer_new_root

   function promised_answer_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(promised_answer_t) :: h
      h%p = capnp_root(msg, err)
   end function promised_answer_read_root

   function promised_answer_question_id_get(h) result(v)
      type(promised_answer_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function promised_answer_question_id_get

   subroutine promised_answer_question_id_set(h, v, err)
      type(promised_answer_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine promised_answer_question_id_set

   function promised_answer_transform_get(h, err) result(l)
      type(promised_answer_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: l
      l = capnp_getp(h%p, 0, err)
   end function promised_answer_transform_get

   function promised_answer_transform_get_elem(h, i, err) result(o)
      type(promised_answer_t), intent(in) :: h
      integer, intent(in) :: i
      integer, intent(out) :: err
      type(promised_answer_op_t) :: o
      type(capnp_ptr_t) :: l
      l = capnp_getp(h%p, 0, err)
      if (err == CAPNP_OK) o%p = capnp_list_get_struct(l, i, err)
   end function promised_answer_transform_get_elem

   function promised_answer_transform_init(h, n, err) result(l)
      type(promised_answer_t), intent(in) :: h
      integer(int64), intent(in) :: n
      integer, intent(out) :: err
      type(capnp_ptr_t) :: l
      l = capnp_new_composite_list(h%p%msg, n, PROMISED_ANSWER_OP_DWORDS, PROMISED_ANSWER_OP_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, l, err)
   end function promised_answer_transform_init

   function promised_answer_op_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(promised_answer_op_t) :: h
      h%p = capnp_new_struct(msg, PROMISED_ANSWER_OP_DWORDS, PROMISED_ANSWER_OP_PWORDS, err)
   end function promised_answer_op_new

   function promised_answer_op_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(promised_answer_op_t) :: h
      h = promised_answer_op_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function promised_answer_op_new_root

   function promised_answer_op_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(promised_answer_op_t) :: h
      h%p = capnp_root(msg, err)
   end function promised_answer_op_read_root

   function promised_answer_op_which(h) result(tag)
      type(promised_answer_op_t), intent(in) :: h
      integer :: tag
      tag = int(capnp_get_u16(h%p, 0_int64))
   end function promised_answer_op_which

   subroutine promised_answer_op_noop_set(h, err)
      type(promised_answer_op_t), intent(in) :: h
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 0_int64, 0_int32, err)
   end subroutine promised_answer_op_noop_set

   function promised_answer_op_get_pointer_field_get(h) result(v)
      type(promised_answer_op_t), intent(in) :: h
      integer(int32) :: v
      v = capnp_get_u16(h%p, 2_int64)
   end function promised_answer_op_get_pointer_field_get

   subroutine promised_answer_op_get_pointer_field_set(h, v, err)
      type(promised_answer_op_t), intent(in) :: h
      integer(int32), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 0_int64, 1_int32, err)
      call capnp_set_u16(h%p, 2_int64, v, err)
   end subroutine promised_answer_op_get_pointer_field_set

   function cap_descriptor_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(cap_descriptor_t) :: h
      h%p = capnp_new_struct(msg, CAP_DESCRIPTOR_DWORDS, CAP_DESCRIPTOR_PWORDS, err)
   end function cap_descriptor_new

   function cap_descriptor_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(cap_descriptor_t) :: h
      h = cap_descriptor_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function cap_descriptor_new_root

   function cap_descriptor_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(cap_descriptor_t) :: h
      h%p = capnp_root(msg, err)
   end function cap_descriptor_read_root

   function cap_descriptor_which(h) result(tag)
      type(cap_descriptor_t), intent(in) :: h
      integer :: tag
      tag = int(capnp_get_u16(h%p, 0_int64))
   end function cap_descriptor_which

   subroutine cap_descriptor_none_set(h, err)
      type(cap_descriptor_t), intent(in) :: h
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 0_int64, 0_int32, err)
   end subroutine cap_descriptor_none_set

   function cap_descriptor_sender_hosted_get(h) result(v)
      type(cap_descriptor_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 4_int64)
   end function cap_descriptor_sender_hosted_get

   subroutine cap_descriptor_sender_hosted_set(h, v, err)
      type(cap_descriptor_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 0_int64, 1_int32, err)
      call capnp_set_u32(h%p, 4_int64, v, err)
   end subroutine cap_descriptor_sender_hosted_set

   function cap_descriptor_sender_promise_get(h) result(v)
      type(cap_descriptor_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 4_int64)
   end function cap_descriptor_sender_promise_get

   subroutine cap_descriptor_sender_promise_set(h, v, err)
      type(cap_descriptor_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 0_int64, 2_int32, err)
      call capnp_set_u32(h%p, 4_int64, v, err)
   end subroutine cap_descriptor_sender_promise_set

   function cap_descriptor_receiver_hosted_get(h) result(v)
      type(cap_descriptor_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 4_int64)
   end function cap_descriptor_receiver_hosted_get

   subroutine cap_descriptor_receiver_hosted_set(h, v, err)
      type(cap_descriptor_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u16(h%p, 0_int64, 3_int32, err)
      call capnp_set_u32(h%p, 4_int64, v, err)
   end subroutine cap_descriptor_receiver_hosted_set

   function cap_descriptor_receiver_answer_get(h, err) result(o)
      type(cap_descriptor_t), intent(in) :: h
      integer, intent(out) :: err
      type(promised_answer_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function cap_descriptor_receiver_answer_get

   function cap_descriptor_receiver_answer_init(h, err) result(o)
      type(cap_descriptor_t), intent(in) :: h
      integer, intent(out) :: err
      type(promised_answer_t) :: o
      call capnp_set_u16(h%p, 0_int64, 4_int32, err)
      o%p = capnp_new_struct(h%p%msg, PROMISED_ANSWER_DWORDS, PROMISED_ANSWER_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function cap_descriptor_receiver_answer_init

   function cap_descriptor_third_party_hosted_get(h, err) result(o)
      type(cap_descriptor_t), intent(in) :: h
      integer, intent(out) :: err
      type(third_party_cap_descriptor_t) :: o
      o%p = capnp_getp(h%p, 0, err)
   end function cap_descriptor_third_party_hosted_get

   function cap_descriptor_third_party_hosted_init(h, err) result(o)
      type(cap_descriptor_t), intent(in) :: h
      integer, intent(out) :: err
      type(third_party_cap_descriptor_t) :: o
      call capnp_set_u16(h%p, 0_int64, 5_int32, err)
      o%p = capnp_new_struct(h%p%msg, THIRD_PARTY_CAP_DESCRIPTOR_DWORDS, THIRD_PARTY_CAP_DESCRIPTOR_PWORDS, err)
      if (err == CAPNP_OK) call capnp_setp(h%p, 0, o%p, err)
   end function cap_descriptor_third_party_hosted_init

   function cap_descriptor_attached_fd_get(h) result(v)
      type(cap_descriptor_t), intent(in) :: h
      integer(int16) :: v
      v = capnp_get_u8(h%p, 2_int64, default=255_int16)
   end function cap_descriptor_attached_fd_get

   subroutine cap_descriptor_attached_fd_set(h, v, err)
      type(cap_descriptor_t), intent(in) :: h
      integer(int16), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u8(h%p, 2_int64, v, err, default=255_int16)
   end subroutine cap_descriptor_attached_fd_set

   function third_party_cap_descriptor_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(third_party_cap_descriptor_t) :: h
      h%p = capnp_new_struct(msg, THIRD_PARTY_CAP_DESCRIPTOR_DWORDS, THIRD_PARTY_CAP_DESCRIPTOR_PWORDS, err)
   end function third_party_cap_descriptor_new

   function third_party_cap_descriptor_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(third_party_cap_descriptor_t) :: h
      h = third_party_cap_descriptor_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function third_party_cap_descriptor_new_root

   function third_party_cap_descriptor_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(third_party_cap_descriptor_t) :: h
      h%p = capnp_root(msg, err)
   end function third_party_cap_descriptor_read_root

   function third_party_cap_descriptor_id_get(h, err) result(q)
      type(third_party_cap_descriptor_t), intent(in) :: h
      integer, intent(out) :: err
      type(capnp_ptr_t) :: q
      q = capnp_getp(h%p, 0, err)
   end function third_party_cap_descriptor_id_get

   subroutine third_party_cap_descriptor_id_set(h, q, err)
      type(third_party_cap_descriptor_t), intent(in) :: h
      type(capnp_ptr_t), intent(in) :: q
      integer, intent(out) :: err
      call capnp_setp(h%p, 0, q, err)
   end subroutine third_party_cap_descriptor_id_set

   function third_party_cap_descriptor_vine_id_get(h) result(v)
      type(third_party_cap_descriptor_t), intent(in) :: h
      integer(int64) :: v
      v = capnp_get_u32(h%p, 0_int64)
   end function third_party_cap_descriptor_vine_id_get

   subroutine third_party_cap_descriptor_vine_id_set(h, v, err)
      type(third_party_cap_descriptor_t), intent(in) :: h
      integer(int64), intent(in) :: v
      integer, intent(out) :: err
      call capnp_set_u32(h%p, 0_int64, v, err)
   end subroutine third_party_cap_descriptor_vine_id_set

end module rpc_capnp
