!> Generated by capnpc-fortran from schema/stream.capnp. Do not edit.
module stream_capnp
   use capnp
   implicit none
   public

   integer, parameter :: STREAM_RESULT_DWORDS = 0
   integer, parameter :: STREAM_RESULT_PWORDS = 0
   type :: stream_result_t
      type(capnp_ptr_t) :: p
   end type stream_result_t

contains

   function stream_result_new(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(stream_result_t) :: h
      h%p = capnp_new_struct(msg, STREAM_RESULT_DWORDS, STREAM_RESULT_PWORDS, err)
   end function stream_result_new

   function stream_result_new_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(stream_result_t) :: h
      h = stream_result_new(msg, err)
      if (err == CAPNP_OK) call capnp_set_root(msg, h%p, err)
   end function stream_result_new_root

   function stream_result_read_root(msg, err) result(h)
      type(capnp_message_t), intent(inout), target :: msg
      integer, intent(out) :: err
      type(stream_result_t) :: h
      h%p = capnp_root(msg, err)
   end function stream_result_read_root

end module stream_capnp
